name: Build and Deploy Blog

on:
  push:
    paths:
      - 'blog/**'
      - '.github/workflows/jekyll-blog.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install and Build Jekyll Blog
        working-directory: blog
        run: |
          gem install bundler
          bundle install
          bundle exec jekyll build --baseurl "/blog"

      - name: Deploy to blog-html
        run: |
          mkdir -p ./blog-html
          rm -rf ./blog-html/*
          cp -r blog/_site/* ./blog-html/
